EmployeeRegister/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAL;
using DAL.Models;
using EmployeeRegister.Models;

namespace EmployeeRegister.Controllers
{
    public class EmployeesController : Controller
    {
        // GET: Employees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var employee = EmployeesManager.Instance.Get(id.Value);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            ViewBag.EmployerId = EmployersManager.Instance.GetSelectList(null);
            return PartialView();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Deleted,Name,Email,EmployerId")] Employee employee)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { success = false, detail = $"Adding {employee.Name} failed." },
                    JsonRequestBehavior.AllowGet);
            }
            else
            {
                if (EmployeesManager.Instance.Add(employee))
                    return Json(new { success = true, parent = employee.EmployerId.HasValue ? $"Employer_{employee.EmployerId}" : null }, JsonRequestBehavior.AllowGet);
                else
                    return Json(new { success = false, detail = $"Adding {employee.Name} failed." },
                        JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var employee = EmployeesManager.Instance.Get(id.Value);
            if (employee == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployerId = EmployersManager.Instance.GetSelectList(employee.EmployerId);
            return PartialView(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Deleted,Name,Email,EmployerId")] Employee employee)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { success = false, detail = $"Editing {employee.Name} failed." }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var oldEmployee = EmployeesManager.Instance.Get(employee.Id);
                if (EmployeesManager.Instance.Modify(employee))
                    return Json(new { success = true, newParent = employee.EmployerId.HasValue ? $"Employer_{employee.EmployerId}" : null, parent = oldEmployee.EmployerId.HasValue ? $"Employer_{oldEmployee.EmployerId}" : null }, JsonRequestBehavior.AllowGet);
                else
                    return Json(new { success = false, detail = $"Editing {employee.Name} failed." }, JsonRequestBehavior.AllowGet);
            }
        }

        // GET: Employees/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var employee = EmployeesManager.Instance.Get(id);
            if (EmployeesManager.Instance.Delete(id))
            {
                return Json(new { success = true, parent = $"Employer_{employee.EmployerId}" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, responseText = "Your message successfuly sent!" }, JsonRequestBehavior.AllowGet);
            }

        }
    }
}

EmployeeRegister/Controllers/EmployersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAL;
using DAL.Models;

namespace EmployeeRegister.Controllers
{
    public class EmployersController : Controller
    {

        // GET: Employers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employer employer = EmployersManager.Instance.Get(id.Value);
            if (employer == null)
            {
                return HttpNotFound();
            }
            return View(employer);
        }

        // GET: Employers/Create
        public ActionResult Create()
        {
            ViewBag.EmployerId = EmployersManager.Instance.GetSelectList(null);
            return PartialView();
        }

        // POST: Employers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Deleted,EmployerId")] Employer employer)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { success = false, detail = $"Adding {employer.Name} failed." },
                    JsonRequestBehavior.AllowGet);
            }
            else
            {
                if (EmployersManager.Instance.Add(employer))
                    return Json(new { success = true, parent = employer.EmployerId.HasValue ? $"Employer_{employer.EmployerId}" : null }, JsonRequestBehavior.AllowGet);
                else
                    return Json(new { success = false, detail = $"Adding {employer.Name} failed." },
                        JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// GET: Employers/Edit/5
        /// </summary>
        /// <param name="id">Employer</param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var employer = EmployersManager.Instance.Get(id.Value);
            if (employer == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployerId = EmployersManager.Instance.GetSelectList(employer.EmployerId);
            return PartialView(employer);
        }

        /// <summary>
        /// POST: Employers/Edit/5
        /// To protect from overposting attacks, please enable the specific properties you want to bind to, for
        /// more details see https://go.microsoft.com/fwlink/?LinkId=317598. 
        /// </summary>
        /// <param name="employer">Employer entity</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Deleted,EmployerId")] Employer employer)
        {
            if (!ModelState.IsValid)
            {
                return Json(new { success = false, detail = $"Editing {employer.Name} failed." }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var oldEmployer = EmployersManager.Instance.Get(employer.Id);
                if (EmployersManager.Instance.Modify(employer))
                    return Json(new { success = true, newParent = employer.EmployerId.HasValue ? $"Employer_{employer.EmployerId}" : null, parent = oldEmployer.EmployerId.HasValue ? $"Employer_{oldEmployer.EmployerId}" : null }, JsonRequestBehavior.AllowGet);
                else
                    return Json(new { success = false, detail = $"Editing {employer.Name} failed." }, JsonRequestBehavior.AllowGet);
            }
        }

        /// <summary>
        /// POST: Employers/Delete/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var employer = EmployersManager.Instance.Get(id);

            if (EmployersManager.Instance.Delete(id))
            {
                return Json(new { success = true, parent = employer.GeneralContractor != null ? $"Employer_{employer.EmployerId}" : null }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, detail = $"Deleting {employer.Name} failed." }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

EmployeeRegister/Controllers/EmploymentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAL;
using DAL.Models;

namespace EmployeeRegister.Controllers
{
    public class EmploymentsController : Controller
    {
        private RegisterEntities db = new RegisterEntities();

        // GET: Employments
        public ActionResult Index()
        {
            return View();
        }

        private Tuple<IEnumerable<Employee>, IEnumerable<Employer>> GetEmployed(int id)
        {
            var employer = EmployersManager.Instance.Get(id);
            var subContractors = EmployersManager.Instance.ListSubContractors(id);
            var employees = employer.Employees.ToList();
            var result=new Tuple<IEnumerable<Employee>, IEnumerable<Employer>>(employees, subContractors);
            return result;
        }

        public ActionResult GetNode(int? id)
        {
            if (id.HasValue)
            {
                var model = GetEmployed(id.Value);
                return PartialView("Node", model);
            }

            var employers = DAL.EmployersManager.Instance.List();
            return PartialView("Root", employers);
        }
    }
}

EmployeeRegister/Views/Employments/Index.cshtml
@{
    ViewBag.Title = "Employment Tree";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/themes/default/style.min.css" />
<div id="TreeContainer" class="col-sm-11 col-lg-5 card">
    <div class="col-sm-12">
        <button class="btn btn-success btn-md" onclick="DetailView.NewEmployer()">New Employer</button>
        <button class="btn btn-success btn-md" onclick="DetailView.NewEmployee()">New Employee</button>
        @Modal.TriggerButton("Delete", "#deleteConfirmation", "btn-danger", "btn-md")
    </div>
    <div class="col-sm-12" id="TreeHeader">
        <hr />
        General contractors:
    </div>
    <div class="col-sm-12" id="TreeContent">
    </div>
</div>
<div id="DetailsContainer" class="col-sm-11 col-lg-6 card">
    <div id="DetailsContent">
        Awaiting selection..
    </div>
</div>

@{
    var buttons = new List<(string label, string style, string size, string onClick)>();
    buttons.Add(("Yes", "btn-warning", "btn-md", $"TreeView.Delete()"));
}
@Modal.Window("deleteConfirmation", "Delete", $"Please confirm if you would like to delete.", buttons)

@section scripts
{
    <script language="javascript">
        $(document).ready(function () {
            DetailView.Initialize(
                'DetailsContainer',
                '@Url.Action("Create", "Employers")',
                '@Url.Action("Create", "Employees")');
            TreeView.Initialize(
                '@Url.Action("GetNode")',
                '@Url.Action("Edit", "Employers")',
                '@Url.Action("Edit", "Employees")',
                '@Url.Action("Delete", "Employers")',
                '@Url.Action("Delete", "Employees")');
        });
    </script>
}

EmployeeRegister/Views/Employments/Node.cshtml
@model Tuple<IEnumerable<DAL.Models.Employee>, IEnumerable<DAL.Models.Employer>>

<ul>
    @{
        foreach (var employee in Model.Item1)
        {
            <li id="Employee_@employee.Id"
                data-jstree='{"icon":"glyphicon glyphicon-user"}'
                data-type="@typeof(DAL.Models.Employee)">
                @employee.Name
            </li>
        }
        foreach (var employer in Model.Item2)
        {
            <li id="Employer_@employer.Id"
                data-jstree='{"icon":"glyphicon glyphicon-home"}'
                data-type="@typeof(DAL.Models.Employer)"
                @if (employer.SubContractors.Count > 0 || employer.Employees.Count > 0) { @: class="jstree-closed"
                }>
                @employer.Name
            </li>
        }
    }
</ul>

EmployeeRegister/Views/Employments/Root.cshtml
@model IEnumerable<DAL.Models.Employer>


<ul>
    @{
        foreach (var employer in Model)
        {
            <li id="Employer_@employer.Id"
                data-jstree='{"icon":"glyphicon glyphicon-home"}'
                data-type="@typeof(DAL.Models.Employer)"
                @if (employer.SubContractors.Count > 0 || employer.Employees.Count > 0) { @: class="jstree-closed"
                }>
                @employer.Name
            </li>
        }
    }
</ul>