EmployeeRegister/Controllers/EmploymentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DAL;
using DAL.Models;

namespace EmployeeRegister.Controllers
{
    public class EmploymentsController : Controller
    {
        private RegisterEntities db = new RegisterEntities();

        // GET: Employments
        public ActionResult Index()
        {
            return View();
        }

        private Tuple<IEnumerable<Employee>, IEnumerable<Employer>> GetEmployed(int id)
        {
            var employer = EmployersManager.Instance.Get(id);
            var subContractors = EmployersManager.Instance.ListSubContractors(id);
            var employees = employer.Employees.ToList();
            var result=new Tuple<IEnumerable<Employee>, IEnumerable<Employer>>(employees, subContractors);
            return result;
        }

        public ActionResult GetNode(int? id)
        {
            if (id.HasValue)
            {
                var model = GetEmployed(id.Value);
                return PartialView("Node", model);
            }

            var employers = DAL.EmployersManager.Instance.List();
            return PartialView("Root", employers);
        }
    }
}

EmployeeRegister/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!-- particles.js container -->
    <div id="particles-js" style="z-index: -10; position:absolute;width: 100%;height: 100%;background-color: white;background-image: url(''); background-repeat: no-repeat;background-size: cover;background-position: 50% 50%;">
    </div>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Employment Register", "Index", "Employments", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Content("~/Elmah")">Error log</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @* Separate Css *@
        <footer style="background-color: orange;position: absolute;left: 0;bottom: 0;height: 50px;width: 100%;overflow: hidden;">
            jsTree under MIT license
            <br/>
            Particles under MIT license
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jstree/3.2.1/jstree.min.js"></script>
    <!-- particles.js source -->
    <script src="http://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script>
    <!-- https://vincentgarreau.com/particles.js/ -->
    @Scripts.Render("~/bundles/employeeRegister")
    @RenderSection("scripts", required: false)

    @* TODO separate file *@
</body>
</html>